# This Dockerfile is for building a ubuntu based image with git installed. The entrypoint is git

FROM ubuntu:16.04

MAINTAINER Antonel Pazargic <antonel.pazargic>@gmail.com

RUN apt-get update && apt-get install -y git

ENTRYPOINT ["git"] 

