VAGRANT_VERSION = '2'
Vagrant.configure(VAGRANT_VERSION) do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.define "vagrant1" do |vagrant1|
    vagrant1.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true
    vagrant1.vm.network "forwarded_port", guest: 443, host: 8443, auto_correct: true
  end

  config.vm.define "vagrant2" do |vagrant2|
    vagrant2.vm.network "forwarded_port", guest: 80, host: 8081, auto_correct: true
    vagrant2.vm.network "forwarded_port", guest: 443, host: 8444, auto_correct: true
  end

  config.vm.define "vagrant3" do |vagrant3|
    vagrant3.vm.network "forwarded_port", guest: 80, host:8082, auto_correct: true
    vagrant3.vm.network "forwarded_port", guest: 443, host:8445, auto_correct: true
  end
end
